/****************************************************************************

Copyright (c) Intel Corporation (2015).

DISCLAIMER OF WARRANTY
NEITHER INTEL NOR ITS SUPPLIERS MAKE ANY REPRESENTATION OR WARRANTY OR
CONDITION OF ANY KIND WHETHER EXPRESS OR IMPLIED (EITHER IN FACT OR BY
OPERATION OF LAW) WITH RESPECT TO THE SOURCE CODE.  INTEL AND ITS SUPPLIERS
EXPRESSLY DISCLAIM ALL WARRANTIES OR CONDITIONS OF MERCHANTABILITY OR
FITNESS FOR A PARTICULAR PURPOSE.  INTEL AND ITS SUPPLIERS DO NOT WARRANT
THAT THE SOURCE CODE IS ERROR-FREE OR THAT OPERATION OF THE SOURCE CODE WILL
BE SECURE OR UNINTERRUPTED AND HEREBY DISCLAIM ANY AND ALL LIABILITY ON
ACCOUNT THEREOF.  THERE IS ALSO NO IMPLIED WARRANTY OF NON-INFRINGEMENT.
SOURCE CODE IS LICENSED TO LICENSEE ON AN "AS IS" BASIS AND NEITHER INTEL
NOR ITS SUPPLIERS WILL PROVIDE ANY SUPPORT, ASSISTANCE, INSTALLATION,
TRAINING OR OTHER SERVICES.  INTEL AND ITS SUPPLIERS WILL NOT PROVIDE ANY
UPDATES, ENHANCEMENTS OR EXTENSIONS.

File Name:      DrmShimPropertyList.h

Description:    List of spoofed DRM properties

Environment:

Notes:

****************************************************************************/

// Plane properties
DECLARE_PLANE_PROPERTY(type)
DECLARE_PLANE_PROPERTY(SRC_X)
DECLARE_PLANE_PROPERTY(SRC_Y)
DECLARE_PLANE_PROPERTY(SRC_W)
DECLARE_PLANE_PROPERTY(SRC_H)
DECLARE_PLANE_PROPERTY(CRTC_X)
DECLARE_PLANE_PROPERTY(CRTC_Y)
DECLARE_PLANE_PROPERTY(CRTC_W)
DECLARE_PLANE_PROPERTY(CRTC_H)
DECLARE_PLANE_PROPERTY(CRTC_ID)
DECLARE_PLANE_PROPERTY(FB_ID)

DECLARE_PLANE_PROPERTY(RRB2)
DECLARE_PLANE_PROPERTY(rotation)
DECLARE_PLANE_PROPERTY_2(render_compression, "render compression")
DECLARE_PLANE_PROPERTY(blend_func)
DECLARE_PLANE_PROPERTY(blend_color)
DECLARE_PLANE_PROPERTY(I915_COLOR_MATRIX)

// CRTC properties
// Panel fitter
DECLARE_CRTC_PROPERTY(I915_PF_X)
DECLARE_CRTC_PROPERTY(I915_PF_Y)
DECLARE_CRTC_PROPERTY(I915_PF_W)
DECLARE_CRTC_PROPERTY(I915_PF_H)
DECLARE_CRTC_PROPERTY(I915_PF_MODE)

DECLARE_CRTC_PROPERTY(I915_DIRTY_X)
DECLARE_CRTC_PROPERTY(I915_DIRTY_Y)
DECLARE_CRTC_PROPERTY(I915_DIRTY_W)
DECLARE_CRTC_PROPERTY(I915_DIRTY_H)
DECLARE_CRTC_PROPERTY(I915_ZORDER)
DECLARE_CRTC_PROPERTY(I915_REFRESH)
DECLARE_CRTC_PROPERTY(I915_WRITEBACK_FB_ID)
DECLARE_CRTC_PROPERTY(I915_MULTIPLANE)
DECLARE_CRTC_PROPERTY(I915_DISPLAY_BPP)
DECLARE_CRTC_PROPERTY(I915_PSR)
DECLARE_CRTC_PROPERTY(I915_COLOR_MATRIX)
DECLARE_CRTC_PROPERTY(I915_BACKGROUND)
