/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Plane properties
DECLARE_PLANE_PROPERTY(type)
DECLARE_PLANE_PROPERTY(SRC_X)
DECLARE_PLANE_PROPERTY(SRC_Y)
DECLARE_PLANE_PROPERTY(SRC_W)
DECLARE_PLANE_PROPERTY(SRC_H)
DECLARE_PLANE_PROPERTY(CRTC_X)
DECLARE_PLANE_PROPERTY(CRTC_Y)
DECLARE_PLANE_PROPERTY(CRTC_W)
DECLARE_PLANE_PROPERTY(CRTC_H)
DECLARE_PLANE_PROPERTY(CRTC_ID)
DECLARE_PLANE_PROPERTY(FB_ID)

DECLARE_PLANE_PROPERTY(RRB2)
DECLARE_PLANE_PROPERTY(rotation)
DECLARE_PLANE_PROPERTY_2(render_compression, "render compression")
DECLARE_PLANE_PROPERTY(blend_func)
DECLARE_PLANE_PROPERTY(blend_color)
DECLARE_PLANE_PROPERTY(I915_COLOR_MATRIX)

// CRTC properties
// Panel fitter
DECLARE_CRTC_PROPERTY(I915_PF_X)
DECLARE_CRTC_PROPERTY(I915_PF_Y)
DECLARE_CRTC_PROPERTY(I915_PF_W)
DECLARE_CRTC_PROPERTY(I915_PF_H)
DECLARE_CRTC_PROPERTY(I915_PF_MODE)

DECLARE_CRTC_PROPERTY(I915_DIRTY_X)
DECLARE_CRTC_PROPERTY(I915_DIRTY_Y)
DECLARE_CRTC_PROPERTY(I915_DIRTY_W)
DECLARE_CRTC_PROPERTY(I915_DIRTY_H)
DECLARE_CRTC_PROPERTY(I915_ZORDER)
DECLARE_CRTC_PROPERTY(I915_REFRESH)
DECLARE_CRTC_PROPERTY(I915_WRITEBACK_FB_ID)
DECLARE_CRTC_PROPERTY(I915_MULTIPLANE)
DECLARE_CRTC_PROPERTY(I915_DISPLAY_BPP)
DECLARE_CRTC_PROPERTY(I915_PSR)
DECLARE_CRTC_PROPERTY(I915_COLOR_MATRIX)
DECLARE_CRTC_PROPERTY(I915_BACKGROUND)
