#!/bin/bash
# $1: statistic name (e.g. partitioned_compositions)
# $2: Builder (CHT|BXT|BYT|VCHT|VBYT|VBXT
# $3: test set (e.g. default)
# $4: test (e.g. Api)
if [[ ${2:0:1} == "V" ]]
then
    BUILDER="Hardware_Composer_Validation_Builder_${2:1}"
else
    BUILDER="Hardware_Composer_Builder_$2"
fi
echo "build,$1"
grep $1 /usr2/jenkins/jobs/$BUILDER/workspace/*/statistics_$3.csv | grep ":$4," | awk -f /usr2/jenkins/bin/statistics/extract_bn_value.awk | sort -n
